# These are supported funding model platforms

github: $GITHUB_USER
ko_fi: $GITHUB_USER
buy_me_a_coffee: $GITHUB_USER

open_collective:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
